name: iatt
description: In Ảnh Trực Tuyến.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.4.0
  shared_preferences: ^2.5.1
  cached_network_image: ^3.3.1
  flutter_dotenv: ^5.1.0
  logger: ^2.0.2+1
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  flutter_svg: ^1.1.5
  sizer: ^2.0.15
  flutter_easyloading: ^3.0.5
  google_fonts: ^4.0.4
  uuid: ^4.5.1
  loading_animation_widget: ^1.3.0
  crypto: ^3.0.6
  qr_flutter: ^4.1.0
  intl: ^0.20.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: PlusJakartaSans
      fonts:
        # - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Black.otf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-BoldItalic.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraBold.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraLight.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Light.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Medium.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-SemiBold.ttf
        # - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Thin.otf
  assets:
    # - .env
    - assets/images/
    - assets/icons/
